import * as fs from 'fs';

const filePath = 'src/components/HurufLibrary.tsx';
let content = fs.readFileSync(filePath, 'utf8');

const updatedArray = `const CLASSICAL_HURUF: HarfItem[] = [
  // 1. Haroof al-Jarr (Prepositions of Genitive)
  {
    id: "bi",
    arabic: "بِـ",
    transliteration: "Bi-",
    englishMeaning: "In / By / With / At",
    attachmentType: "prefixed",
    category: "preposition",
    grammaticalEffect: "Forces noun into Genitive (Majrūr) case.",
    syntacticRule: "Fused immediately as a prefix.",
    quranicExampleArabic: "بِسْمِ اللَّهِ",
    quranicExampleTranslation: "In the name of Allah",
    mnemonic: "Bi connects with Kasrah"
  },
  {
    id: "ta",
    arabic: "تَـ",
    transliteration: "Ta-",
    englishMeaning: "By... (Oath to Allah)",
    attachmentType: "prefixed",
    category: "preposition",
    grammaticalEffect: "Forces the word 'Allah' into Genitive oath state (Majrūr).",
    syntacticRule: "Direct prefix, exclusively attached to string 'الله'.",
    quranicExampleArabic: "تَاللَّهِ لَقَدْ آثَرَكَ اللَّهُ",
    quranicExampleTranslation: "By Allah, indeed Allah has preferred you",
    mnemonic: "Only used with Allah for Oaths"
  },
  {
    id: "wa_oath",
    arabic: "وَ",
    transliteration: "Wa (Oath)",
    englishMeaning: "By... (Oath)",
    attachmentType: "prefixed",
    category: "preposition",
    grammaticalEffect: "Preposition for an oath causing Genitive (Majrūr).",
    syntacticRule: "Written adjacent to the subsequent word like a prefix.",
    quranicExampleArabic: "وَالْعَصْرِ",
    quranicExampleTranslation: "By the passage of time",
    mnemonic: "Cosmic Oaths (Sun, Moon, Time)"
  },
  {
    id: "ka",
    arabic: "كَـ",
    transliteration: "Ka-",
    englishMeaning: "Like / As (comparison)",
    attachmentType: "prefixed",
    category: "preposition",
    grammaticalEffect: "Forces noun into Genitive (Majrūr). Used for direct comparison.",
    syntacticRule: "Attached as a direct prefix.",
    quranicExampleArabic: "كَعَصْفٍ مَأْكُولٍ",
    quranicExampleTranslation: "Like chewed straw/husks",
    mnemonic: "'Ka' is for morphing/comparison"
  },
  {
    id: "li",
    arabic: "لِـ",
    transliteration: "Li-",
    englishMeaning: "For / To / Belonging to",
    attachmentType: "prefixed",
    category: "preposition",
    grammaticalEffect: "Forces noun into Genitive (Majrūr).",
    syntacticRule: "Prefixed directly to the noun.",
    quranicExampleArabic: "الْحَمْدُ لِلَّهِ",
    quranicExampleTranslation: "All praise belongs to Allah",
    mnemonic: "Li means 'Leans to'"
  },
  {
    id: "min",
    arabic: "مِنْ",
    transliteration: "Min",
    englishMeaning: "From / Out of / Among",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Forces noun into Genitive case. Vowel changes to (مِنَ) if preceding sukun.",
    syntacticRule: "Stands alone.",
    quranicExampleArabic: "مِنَ الْجِنَّةِ وَالنَّاسِ",
    quranicExampleTranslation: "From among the Jinn and mankind",
    mnemonic: "Origin / Extraction"
  },
  {
    id: "fi",
    arabic: "فِي",
    transliteration: "Fī",
    englishMeaning: "In / Inside of",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Forces noun into Genitive (Majrūr). Spatial particle.",
    syntacticRule: "Written standalone.",
    quranicExampleArabic: "فِي قُلُوبِهِمْ مَرَضٌ",
    quranicExampleTranslation: "In their hearts is a disease",
    mnemonic: "Fi fills the inside"
  },
  {
    id: "an",
    arabic: "عَنْ",
    transliteration: "'An",
    englishMeaning: "About / Away from",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Governs noun into Genitive state.",
    syntacticRule: "Stands alone.",
    quranicExampleArabic: "رَضِيَ اللَّهُ عَنْهُمْ",
    quranicExampleTranslation: "Allah is pleased with them",
    mnemonic: "Distancing / 'away from'"
  },
  {
    id: "ala",
    arabic: "عَلَىٰ",
    transliteration: "'Alā",
    englishMeaning: "On / Upon",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Causes Genitive casing. Indicates high authority.",
    syntacticRule: "Freestanding word. Modifies spelling to (عَلَيْـ) if suffix pronouns attached.",
    quranicExampleArabic: "عَلَى الْعَرْشِ اسْتَوَىٰ",
    quranicExampleTranslation: "Established Himself upon the Throne",
    mnemonic: "Elevated / On top of"
  },
  {
    id: "hatta",
    arabic: "حَتَّىٰ",
    transliteration: "Hattā",
    englishMeaning: "Until / Up to",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Governs next noun into Genitive, or makes present verbs subjunctive.",
    syntacticRule: "Stands alone.",
    quranicExampleArabic: "حَتَّىٰ مَطْلَعِ الْفَجْرِ",
    quranicExampleTranslation: "Until the emergence of the dawn",
    mnemonic: "Halted at the limit (until)"
  },
  {
    id: "ila",
    arabic: "إِلَىٰ",
    transliteration: "Ilā",
    englishMeaning: "To / Towards",
    attachmentType: "standalone",
    category: "preposition",
    grammaticalEffect: "Causes Majrūr (Genitive) casing.",
    syntacticRule: "Changes to إِلَيْـ before suffix pronouns.",
    quranicExampleArabic: "إِلَى اللَّهِ الْمَصِيرُ",
    quranicExampleTranslation: "Towards Allah is the final return",
    mnemonic: "Directional target"
  },

  // 2. Conjunctions (Haroof al-Atf)
  {
    id: "wa_conj",
    arabic: "وَ",
    transliteration: "Wa",
    englishMeaning: "And",
    attachmentType: "prefixed",
    category: "conjunction",
    grammaticalEffect: "Coordinates grammar identically.",
    syntacticRule: "Always written adjacent to the subsequent word.",
    quranicExampleArabic: "الْإِنسِ وَالْجِنِّ",
    quranicExampleTranslation: "Mankind and Jinn",
    mnemonic: "Creates a linked pair"
  },
  {
    id: "fa",
    arabic: "فَـ",
    transliteration: "Fa-",
    englishMeaning: "So / Then",
    attachmentType: "prefixed",
    category: "conjunction",
    grammaticalEffect: "Connects two events sequentially",
    syntacticRule: "Fused immediately as a prefix.",
    quranicExampleArabic: "فَإِذَا جَاءَ وَعْدُ رَبِّي",
    quranicExampleTranslation: "So when the promise of my Lord comes...",
    mnemonic: "Fast / Immediate cause and effect"
  },
  {
    id: "thumma",
    arabic: "ثُمَّ",
    transliteration: "Thumma",
    englishMeaning: "Then / Afterward",
    attachmentType: "standalone",
    category: "conjunction",
    grammaticalEffect: "Coordinates two sentences or nouns.",
    syntacticRule: "Introduces chronologically delayed sequence.",
    quranicExampleArabic: "ثُمَّ خَلَقْنَا النُّطْفَةَ عَلَقَةً",
    quranicExampleTranslation: "Then We made the sperm-drop into a clinging clot",
    mnemonic: "Delayed transition"
  },
  {
    id: "aw",
    arabic: "أَوْ",
    transliteration: "Aw",
    englishMeaning: "Or / Either",
    attachmentType: "standalone",
    category: "conjunction",
    grammaticalEffect: "Offers alternative options.",
    syntacticRule: "Freestanding.",
    quranicExampleArabic: "أَوْ كَصَيِّبٍ مِّنَ السَّمَاءِ",
    quranicExampleTranslation: "Or like a rainstorm from the sky",
    mnemonic: "Another Way (Alternative)"
  },
  {
    id: "bal",
    arabic: "بَلْ",
    transliteration: "Bal",
    englishMeaning: "Rather / But",
    attachmentType: "standalone",
    category: "conjunction",
    grammaticalEffect: "Corrects/Cancels previous statement.",
    syntacticRule: "Freestanding.",
    quranicExampleArabic: "بَلْ هُمْ فِي شَكٍّ يَلْعَبُونَ",
    quranicExampleTranslation: "Rather, they are in doubt, amusing themselves",
    mnemonic: "Backtracks to state reality"
  },

  // 3. Haroof al-Nasb 'Inna and her sisters'
  {
    id: "inna",
    arabic: "إِنَّ",
    transliteration: "Inna",
    englishMeaning: "Indeed / Verily",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes the subject noun accusative (Mansūb).",
    syntacticRule: "Precedes a nominal sentence.",
    quranicExampleArabic: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
    quranicExampleTranslation: "Indeed, Allah is with those who are patient.",
    mnemonic: "Maximum certainty at the start"
  },
  {
    id: "anna",
    arabic: "أَنَّ",
    transliteration: "Anna",
    englishMeaning: "That (Indeed)",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes subject noun accusative (Mansūb).",
    syntacticRule: "Occurs within a sentence to connect thoughts.",
    quranicExampleArabic: "وَاعْلَمُوا أَنَّ اللَّهَ سَمِيعٌ عَلِيمٌ",
    quranicExampleTranslation: "And know that Allah is Hearing and Knowing",
    mnemonic: "Connects clauses firmly"
  },
  {
    id: "ka_anna",
    arabic: "كَأَنَّ",
    transliteration: "Ka'anna",
    englishMeaning: "As if",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes subject noun accusative.",
    syntacticRule: "Freestanding comparison.",
    quranicExampleArabic: "كَأَنَّهُمْ خُشُبٌ مُّسَنَّدَةٌ",
    quranicExampleTranslation: "As if they were propped up timbers",
    mnemonic: "Ka (Like) + Anna (That) = As if"
  },
  {
    id: "lakinna",
    arabic: "لَٰكِنَّ",
    transliteration: "Lākinna",
    englishMeaning: "But / However",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes subject noun accusative.",
    syntacticRule: "Freestanding contrast.",
    quranicExampleArabic: "لَٰكِنَّ اللَّهَ ذُو فَضْلٍ",
    quranicExampleTranslation: "But Allah is the possessor of bounty",
    mnemonic: "Lacks/Looks for contrast"
  },
  {
    id: "la_alla",
    arabic: "لَعَلَّ",
    transliteration: "La'alla",
    englishMeaning: "Perhaps / So that",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes subject accusative.",
    syntacticRule: "Freestanding expression of hope.",
    quranicExampleArabic: "لَعَلَّكُمْ تَتَّقُونَ",
    quranicExampleTranslation: "So that you may become righteous",
    mnemonic: "Leaves hope/expectation"
  },
  {
    id: "layta",
    arabic: "لَيْتَ",
    transliteration: "Layta",
    englishMeaning: "If only / Would that",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Makes subject accusative.",
    syntacticRule: "Freestanding impossible desire.",
    quranicExampleArabic: "يَا لَيْتَنِي كُنتُ تُرَابًا",
    quranicExampleTranslation: "Oh, I wish I were dust",
    mnemonic: "Lamenting the impossible"
  },

  // 4. Negation & Interrogation
  {
    id: "la_nafy",
    arabic: "لَا",
    transliteration: "Lā",
    englishMeaning: "No / Not",
    attachmentType: "standalone",
    category: "negation",
    grammaticalEffect: "Negation makes nouns accusative. Prohibition makes verbs jussive.",
    syntacticRule: "Freestanding particle.",
    quranicExampleArabic: "لَا رَيْبَ فِيهِ",
    quranicExampleTranslation: "No doubt whatsoever inside it",
    mnemonic: "Absolute Void"
  },
  {
    id: "ma",
    arabic: "مَا",
    transliteration: "Mā",
    englishMeaning: "Not / What",
    attachmentType: "standalone",
    category: "negation",
    grammaticalEffect: "Negates past tense verbs or acts as relative pronoun.",
    syntacticRule: "Freestanding.",
    quranicExampleArabic: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ",
    quranicExampleTranslation: "Your Lord has not taken leave of you, nor has He detested",
    mnemonic: "Missing action in the past"
  },
  {
    id: "lam",
    arabic: "لَمْ",
    transliteration: "Lam",
    englishMeaning: "Did not",
    attachmentType: "standalone",
    category: "negation",
    grammaticalEffect: "Negates present tense action and flips to past, forcing Jussive (Majzūm).",
    syntacticRule: "Standalone before present verbs.",
    quranicExampleArabic: "لَمْ يَلِدْ وَلَمْ يُولَدْ",
    quranicExampleTranslation: "He neither begets nor is born",
    mnemonic: "Leaps back to the past"
  },
  {
    id: "lan",
    arabic: "لَنْ",
    transliteration: "Lan",
    englishMeaning: "Never",
    attachmentType: "standalone",
    category: "negation",
    grammaticalEffect: "Negates future absolutely. Next verb becomes Subjunctive (Mansūb).",
    syntacticRule: "Standalone before present verbs.",
    quranicExampleArabic: "لَن تَنَالُوا الْبِرَّ",
    quranicExampleTranslation: "Never will you attain righteousness",
    mnemonic: "Locks the future"
  },
  {
    id: "hal",
    arabic: "هَلْ",
    transliteration: "Hal",
    englishMeaning: "Is / Are / Do",
    attachmentType: "standalone",
    category: "interrogative",
    grammaticalEffect: "No direct case-ending effect.",
    syntacticRule: "Precedes sentence.",
    quranicExampleArabic: "هَلْ أَتَىٰ عَلَى الْإِنسَانِ حِينٌ مِّنَ الدَّهْرِ",
    quranicExampleTranslation: "Has there [not] come upon man a period of time...",
    mnemonic: "Harvests a Yes/No"
  },
  {
    id: "a",
    arabic: "أَ",
    transliteration: "A-",
    englishMeaning: "Is / Are / Do",
    attachmentType: "prefixed",
    category: "interrogative",
    grammaticalEffect: "No case effect.",
    syntacticRule: "Prefixed directly to ask yes/no.",
    quranicExampleArabic: "أَأَنتُمْ أَشَدُّ خَلْقًا أَمِ السَّمَاءُ",
    quranicExampleTranslation: "Are you a more difficult creation or is the heaven?",
    mnemonic: "A sharp, quick inquiry"
  },

  // 5. Exception, Vocative, and Conditionals
  {
    id: "illa",
    arabic: "إِلَّا",
    transliteration: "Illā",
    englishMeaning: "Except / But",
    attachmentType: "standalone",
    category: "exception",
    grammaticalEffect: "Can force noun to accusative.",
    syntacticRule: "Freestanding.",
    quranicExampleArabic: "لَا إِلَٰهَ إِلَّا اللَّهُ",
    quranicExampleTranslation: "There is no deity except Allah",
    mnemonic: "Isolates the exception"
  },
  {
    id: "ya",
    arabic: "يَا",
    transliteration: "Yā",
    englishMeaning: "O...! (Vocative)",
    attachmentType: "standalone",
    category: "vocative",
    grammaticalEffect: "Forces addressed noun to nominative.",
    syntacticRule: "Standalone vocative.",
    quranicExampleArabic: "يَا أَيُّهَا النَّاسُ",
    quranicExampleTranslation: "O mankind...!",
    mnemonic: "Yells out to call someone"
  },
  {
    id: "in_cond",
    arabic: "إِنْ",
    transliteration: "In",
    englishMeaning: "If / Not",
    attachmentType: "standalone",
    category: "conditional",
    grammaticalEffect: "Causes conditional clauses to become jussive.",
    syntacticRule: "Precedes verbs.",
    quranicExampleArabic: "إِن يَنصُرْكُمُ اللَّهُ فَلَا غَالِبَ لَكُمْ",
    quranicExampleTranslation: "If Allah should aid you, no one can overcome you",
    mnemonic: "Initiates conditions"
  },

  // 6. Tense / Emphasis
  {
    id: "qad",
    arabic: "قَدْ",
    transliteration: "Qad",
    englishMeaning: "Already / Indeed",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Before past verbs: denotes certainty.",
    syntacticRule: "Freestanding before verbs.",
    quranicExampleArabic: "قَدْ أَفْلَحَ الْمُؤْمِنُونَ",
    quranicExampleTranslation: "Certainly will the believers have succeeded",
    mnemonic: "Quantifies certainty"
  },
  {
    id: "sawfa",
    arabic: "سَوْفَ",
    transliteration: "Sawfa",
    englishMeaning: "Will / Soon (Far future)",
    attachmentType: "standalone",
    category: "emphasis",
    grammaticalEffect: "Forces present verb to future tense.",
    syntacticRule: "Standalone before present verbs.",
    quranicExampleArabic: "وَسَوْفَ تَعْلَمُونَ",
    quranicExampleTranslation: "And you will come to know",
    mnemonic: "Sweeps into the distant future"
  },
  {
    id: "sa",
    arabic: "سَـ",
    transliteration: "Sa-",
    englishMeaning: "Will / Very Soon",
    attachmentType: "prefixed",
    category: "emphasis",
    grammaticalEffect: "Changes to immediate future.",
    syntacticRule: "Prefixed to present tense verbs.",
    quranicExampleArabic: "سَيَقُولُ السُّفَهَاءُ",
    quranicExampleTranslation: "The foolish among the people will say",
    mnemonic: "Soon..."
  }
];`;

content = content.replace(/const CLASSICAL_HURUF: HarfItem\[\] = \[[\s\S]*?\];\n/, updatedArray + '\n');
fs.writeFileSync(filePath, content);
console.log('Update complete!');
